export enum SignupStatus {
  PENDING = "PENDING",
  ACCEPTED = "ACCEPTED",
  REJECTED = "REJECTED",
}

export enum ROLES {
  SUDO_ADMIN = "SUDO_ADMIN",
  ADMIN = "ADMIN",
  USER = "USER",
  STUDENT = "STUDENT",
}

export enum BORROWER_STATUS {
  BORROWED = "BORROWED",
  RETURNED = "RETURNED",
}

export enum STATUS_CODE {
  SUCCESS = 200,
  CREATED = 201,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  INTERNAL_SERVER_ERROR = 500,
}
